project_name: little_boxes
version: 2

builds:
  - builder: rust
    binary: little_boxes
    dir: .
    targets:
      - x86_64-unknown-linux-gnu
      - aarch64-unknown-linux-gnu
      - x86_64-apple-darwin
      - aarch64-apple-darwin
    flags:
      - --release

archives:
  - name_template: '{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}'
    formats:
      - tar.gz
    files:
      - LICENSE*
      - README.md

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
