pub struct Charset {
    pub horizontal: char,
    pub vertical: char,
    pub corner_up_left: char,
    pub corner_up_right: char,
    pub corner_down_left: char,
    pub corner_down_right: char,
    pub t_right: char,
    pub t_left: char,
}

pub fn get_charset(input: &str) -> Charset {
    match input {
        "thick" => Charset {
            horizontal: '━',
            vertical: '┃',
            corner_up_left: '┏',
            corner_up_right: '┓',
            corner_down_left: '┗',
            corner_down_right: '┛',
            t_right: '┣',
            t_left: '┫',
        },
        "thin" => Charset {
            horizontal: '─',
            vertical: '│',
            corner_up_left: '┌',
            corner_up_right: '┐',
            corner_down_left: '└',
            corner_down_right: '┘',
            t_right: '├',
            t_left: '┤',
        },
        "double" => Charset {
            horizontal: '═',
            vertical: '║',
            corner_up_left: '╔',
            corner_up_right: '╗',
            corner_down_left: '╚',
            corner_down_right: '╝',
            t_right: '╠',
            t_left: '╣',
        },
        "box" => Charset {
            horizontal: '█',
            vertical: '█',
            corner_up_left: '█',
            corner_up_right: '█',
            corner_down_left: '█',
            corner_down_right: '█',
            t_right: '█',
            t_left: '█',
        },
        "rounded" => Charset {
            horizontal: '─',
            vertical: '│',
            corner_up_left: '╭',
            corner_up_right: '╮',
            corner_down_left: '╰',
            corner_down_right: '╯',
            t_right: '├',
            t_left: '┤',
        },
        "dot" => Charset {
            horizontal: '⠶',
            vertical: '⣿',
            corner_up_left: '⣶',
            corner_up_right: '⣶',
            corner_down_left: '⠿',
            corner_down_right: '⠿',
            t_right: '⡷',
            t_left: '⢾',
        },
        _ => panic!("Invalid charset name. This should not be possable!"),
    }
}
