.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH little_boxes 1  "little_boxes 1.7.0" 
.SH NAME
little_boxes \- Adds boxes around stdin. Optionally adds a title
.SH SYNOPSIS
\fBlittle_boxes\fR [\fB\-t\fR|\fB\-\-title\fR] [\fB\-c\fR|\fB\-\-charset\fR] [\fB\-f\fR|\fB\-\-file\fR] [\fB\-\-all\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] 
.SH DESCRIPTION
Adds boxes around stdin. Optionally adds a title
.SH OPTIONS
.TP
\fB\-t\fR, \fB\-\-title\fR=\fITITLE\fR
Add a title to the box
.TP
\fB\-c\fR, \fB\-\-charset\fR=\fICHARSET\fR [default: thick]
The charset to draw the box with
.br

.br
[\fIpossible values: \fRthick, thin, double, box, rounded, dot]
.TP
\fB\-f\fR, \fB\-\-file\fR=\fIFILE\fR
Read input from a file instead of stdin
.TP
\fB\-\-all\fR
Compare all charsets
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.SH VERSION
v1.7.0
.SH AUTHORS
Gio d\*(AqAmelio <gio@damelio.net>
