pub struct Charset {
    pub horizontal_top: char,
    pub horizontal_bottom: char,
    pub vertical: char,
    pub corner_up_left: char,
    pub corner_up_right: char,
    pub corner_down_left: char,
    pub corner_down_right: char,
    pub t_right: char,
    pub t_left: char,
}

pub fn get_charset(input: &str) -> Charset {
    match input {
        "thick" => Charset {
            horizontal_top: '━',
            horizontal_bottom: '━',
            vertical: '┃',
            corner_up_left: '┏',
            corner_up_right: '┓',
            corner_down_left: '┗',
            corner_down_right: '┛',
            t_right: '┣',
            t_left: '┫',
        },
        "thin" => Charset {
            horizontal_top: '─',
            horizontal_bottom: '─',
            vertical: '│',
            corner_up_left: '┌',
            corner_up_right: '┐',
            corner_down_left: '└',
            corner_down_right: '┘',
            t_right: '├',
            t_left: '┤',
        },
        "double" => Charset {
            horizontal_top: '═',
            horizontal_bottom: '═',
            vertical: '║',
            corner_up_left: '╔',
            corner_up_right: '╗',
            corner_down_left: '╚',
            corner_down_right: '╝',
            t_right: '╠',
            t_left: '╣',
        },
        "box" => Charset {
            horizontal_top: '▄',
            horizontal_bottom: '▀',
            vertical: '█',
            corner_up_left: '▄',
            corner_up_right: '▄',
            corner_down_left: '▀',
            corner_down_right: '▀',
            t_right: '█',
            t_left: '█',
        },
        "rounded" => Charset {
            horizontal_top: '─',
            horizontal_bottom: '─',
            vertical: '│',
            corner_up_left: '╭',
            corner_up_right: '╮',
            corner_down_left: '╰',
            corner_down_right: '╯',
            t_right: '├',
            t_left: '┤',
        },
        "dot" => Charset {
            horizontal_top: '⠶',
            horizontal_bottom: '⠶',
            vertical: '⣿',
            corner_up_left: '⣶',
            corner_up_right: '⣶',
            corner_down_left: '⠿',
            corner_down_right: '⠿',
            t_right: '⡷',
            t_left: '⢾',
        },
        "ascii" => Charset {
            horizontal_top: '-',
            horizontal_bottom: '-',
            vertical: '|',
            corner_up_left: '+',
            corner_up_right: '+',
            corner_down_left: '+',
            corner_down_right: '+',
            t_right: '-',
            t_left: '-',
        },
        _ => panic!("Invalid charset name. This should not be possable!"),
    }
}
