name: Nix
on: [push, pull_request]

jobs:
  build:
    name: Build Nix targets
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v3
      - uses: cachix/cachix-action@v12
        with:
          name: giodamelio
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix-shell --run "echo OK"
      - name: Build default package
        run: nix build
      - name: Actually run the thing!
        run: ls -l | nix run
