name: Rust
on: [push]
jobs:
  test:
    name: Test on Rust ${{ matrix.rust_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust_version: [stable, beta]
    steps:
    - uses: actions/checkout@master
    - name: Set Rust version
      run: rustup default ${{ matrix.rust_version }}
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
